


export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";


export const CONFIRMED_ORDER_REQUEST = "CONFIRMED_ORDER_REQUEST";
export const CONFIRMED_ORDER_SUCCESS = "CONFIRMED_ORDER_SUCCESS";
export const CONFIRMED_ORDER_FAILURE = "CONFIRMED_ORDER_FAILURE";

export const PLACED_ORDER_REQUEST = "PLACED_ORDER_REQUEST";
export const PLACED_ORDER_SUCCESS = "PLACED_ORDER_SUCCESS";
export const PLACED_ORDER_FAILURE = "PLACED_ORDER_FAILURE";

export const DELIVERED_ORDER_REQUEST = "DELIVERED_ORDER_REQUEST";
export const DELIVERED_ORDER_SUCCESS = "DELIVERED_ORDER_SUCCESS";
export const DELIVERED_ORDER_FAILURE = "DELIVERED_ORDER_FAILURE";

export const CANCLE_ORDER_REQUEST = "CANCLE_ORDER_REQUEST";
export const CANCLE_ORDER_SUCCESS = "CANCLE_ORDER_SUCCESS";
export const CANCLE_ORDER_FAILURE = "CANCLE_ORDER_FAILURE";

export const SHIPPEED_ORDER_REQUEST = "SHIPPEED_ORDER_REQUEST";
export const SHIPPEED_ORDER_SUCCESS = "SHIPPEED_ORDER_SUCCESS";
export const SHIPPEED_ORDER_FAILURE = "SHIPPEED_ORDER_FAILURE";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";

